apiVersion: v1
kind: Pod
metadata:
  name: configured-pod
spec:
  containers:
    - image: nginx:1.19.0
      name: app
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: backend-config